[project]
name = "rose"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sonder Merak", email = "merak19981999@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "concurrent-log-handler>=0.9.25",
    "icecream>=2.1.3",
]

[project.scripts]
rose = "rose:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
